name: Build

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_SERVER_URL: ${{ secrets.TEST_SERVER_URL }}
      ACROLINX_API_TOKEN: ${{ secrets.ACROLINX_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          install-chromedriver: true
          install-dependencies: true
      - run: ${{ steps.setup-chrome.outputs.chrome-path }} --version
      - run: echo CHROME_BIN_PATH=${{ steps.setup-chrome.outputs.chrome-path }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build And Run Tests
        run: |
          npm ci
          npm run build
          npm run test
